sudo: required
services:
  - docker

before_install:
  - docker build -t ankurdocker1998/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ankurdocker1998/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-2-378063356886"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"